### ISSUE TITLE
where is crossdocked_pocket10_name2id.pt??

### ISSUE THREAD

**Issue by orgw** [luost26/3D-Generative-SBDD#18] opened 2022-04-04 04:24 UTC
FileNotFoundError: [Errno 2] No such file or directory: './data/crossdocked_pocket10_name2id.pt'

Thanks

**Comment by luost26** [comment] 2022-04-04 04:25
Duplicate of #10 

Please refer to the above issue. Thanks.

**Closed by luost26** 2022-04-04 04:25 UTC
